name: site
version: 0.1.0.0
author: "vekatze"
maintainer: "vekatze@icloud.com"

default-extensions:
  - OverloadedStrings
  - TupleSections

dependencies:
  - aeson
  - base
  - containers
  - data-default-class
  - filepath
  - hakyll
  - mtl
  - pandoc
  - text
  - time
  - unordered-containers

executables:
  site:
    main: Main.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wall
